// data.js
const hostels = [
  {
    "id": "9c6fb00d-f454-4809-9084-460bdd348a2b",
    "owner": "John Doe",
    "hostelName": "Professional Lodges",
    "sector": "Sector 17",
    "hostelAddress": "123 Main St, City, Country",
    "phone": "1234567890",
    "email": "johndoe@example.com",
    "startingPrice": 1000,
    "Wifi": true,
    "Parking": "Cars and Bike",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": true,
    "Laundry": true,
    "cleaning": false,
    "Mess": "2 times a day",
    "Furnished": true,
    "UPS": true,
    "description": "This hostel is amazing",
    "images": [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRDIFBoq6kFzBQE3_4mwWDo2mVfgJ-In8msA&s",
      "https://www.kayak.com/news/wp-content/uploads/sites/19/2023/08/THEME_HOTEL_HOSTEL_BEDROOM-shutterstock-portfolio_1708374559.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRDIFBoq6kFzBQE3_4mwWDo2mVfgJ-In8msA&s"
    ]
  },
  {
    "owner": "John Doe",
    "hostelName": "Professional Lodges",
    "sector": "Sector 17",
    "hostelAddress": "123 Main St, City, Country",
    "phone": "1234567890",
    "email": "johndoe@example.com",
    "startingPrice": 1000,
    "Wifi": true,
    "Parking": "Cars and Bike",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": true,
    "Laundry": true,
    "cleaning": true,
    "Mess": "2 times a day",
    "Furnished": true,
    "UPS": true
  },
  {
    "owner": "Jane Smith",
    "hostelName": "Comfort Stay",
    "sector": "Sector 12",
    "hostelAddress": "456 Elm St, City, Country",
    "phone": "2345678901",
    "email": "janesmith@example.com",
    "startingPrice": 1200,
    "Wifi": true,
    "Parking": "Bike only",
    "Kitchen": true,
    "Geyser": true,
    "AC": false,
    "AirCooler": true,
    "Laundry": false,
    "cleaning": true,
    "Mess": "3 times a day",
    "Furnished": true,
    "UPS": false
  },
  {
    "owner": "Robert Brown",
    "hostelName": "Elite Hostel",
    "sector": "Sector 22",
    "hostelAddress": "789 Pine St, City, Country",
    "phone": "3456789012",
    "email": "robertbrown@example.com",
    "startingPrice": 1500,
    "Wifi": true,
    "Parking": "Cars and Bike",
    "Kitchen": false,
    "Geyser": true,
    "AC": true,
    "AirCooler": false,
    "Laundry": true,
    "cleaning": false,
    "Mess": "1 time a day",
    "Furnished": false,
    "UPS": true
  },
  {
    "owner": "Emily White",
    "hostelName": "Budget Stay",
    "sector": "Sector 8",
    "hostelAddress": "101 Maple St, City, Country",
    "phone": "4567890123",
    "email": "emilywhite@example.com",
    "startingPrice": 900,
    "Wifi": false,
    "Parking": "Bike only",
    "Kitchen": true,
    "Geyser": false,
    "AC": false,
    "AirCooler": true,
    "Laundry": true,
    "cleaning": true,
    "Mess": "2 times a day",
    "Furnished": true,
    "UPS": false
  },
  {
    "owner": "Michael Green",
    "hostelName": "Luxury Living",
    "sector": "Sector 19",
    "hostelAddress": "202 Birch St, City, Country",
    "phone": "5678901234",
    "email": "michaelgreen@example.com",
    "startingPrice": 2000,
    "Wifi": true,
    "Parking": "Cars only",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": true,
    "Laundry": false,
    "cleaning": true,
    "Mess": "3 times a day",
    "Furnished": true,
    "UPS": true
  },
  {
    "owner": "Sarah Johnson",
    "hostelName": "Student Haven",
    "sector": "Sector 5",
    "hostelAddress": "303 Cedar St, City, Country",
    "phone": "6789012345",
    "email": "sarahjohnson@example.com",
    "startingPrice": 1100,
    "Wifi": true,
    "Parking": "Cars and Bike",
    "Kitchen": false,
    "Geyser": true,
    "AC": false,
    "AirCooler": true,
    "Laundry": true,
    "cleaning": true,
    "Mess": "1 time a day",
    "Furnished": false,
    "UPS": false
  },
  {
    "owner": "David Wilson",
    "hostelName": "Comfort Inn",
    "sector": "Sector 13",
    "hostelAddress": "404 Oak St, City, Country",
    "phone": "7890123456",
    "email": "davidwilson@example.com",
    "startingPrice": 1300,
    "Wifi": true,
    "Parking": "Cars only",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": false,
    "Laundry": true,
    "cleaning": true,
    "Mess": "2 times a day",
    "Furnished": true,
    "UPS": true
  },
  {
    "owner": "Laura Lee",
    "hostelName": "Home Away",
    "sector": "Sector 9",
    "hostelAddress": "505 Spruce St, City, Country",
    "phone": "8901234567",
    "email": "lauralee@example.com",
    "startingPrice": 1400,
    "Wifi": false,
    "Parking": "Bike only",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": true,
    "Laundry": false,
    "cleaning": true,
    "Mess": "3 times a day",
    "Furnished": true,
    "UPS": false
  },
  {
    "owner": "James Miller",
    "hostelName": "City Hostels",
    "sector": "Sector 15",
    "hostelAddress": "606 Willow St, City, Country",
    "phone": "9012345678",
    "email": "jamesmiller@example.com",
    "startingPrice": 1600,
    "Wifi": true,
    "Parking": "Cars and Bike",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": false,
    "Laundry": true,
    "cleaning": true,
    "Mess": "2 times a day",
    "Furnished": true,
    "UPS": true
  },
  {
    "owner": "Olivia Martinez",
    "hostelName": "Urban Stay",
    "sector": "Sector 20",
    "hostelAddress": "707 Pinecone St, City, Country",
    "phone": "0123456789",
    "email": "oliviamartinez@example.com",
    "startingPrice": 1800,
    "Wifi": true,
    "Parking": "Cars and Bike",
    "Kitchen": true,
    "Geyser": true,
    "AC": true,
    "AirCooler": true,
    "Laundry": true,
    "cleaning": true,
    "Mess": "3 times a day",
    "Furnished": true,
    "UPS": true
  }
];

export default hostels;
